### ISSUE TITLE
ClientCert.URI should be a slice of strings

### ISSUE THREAD

**Issue by cbroglie** [alecholmes/xfccparser#2]
Like DNS SANs, there can be multiple URI SANs on a client cert. From https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert:
```
The URI type Subject Alternative Name field of the current client certificate. A client certificate may contain multiple URI type Subject Alternative Names, each will be a separate key-value pair.
```
But unlike DNS, the current implementation only supports a single URI SAN:
```go
case "URI":
	cert.URI = field.Value
case "DNS":
	cert.DNS = append(cert.DNS, field.Value)
```
This is just something I noticed, but it isn't likely to be an issue for most users in practice since SPIFFE doesn't allow multiple URI SANs.

I'd be happy to submit a PR if you're OK with a breaking change.

**Comment by alecholmes** [comment]
Thanks for pointing that out. I had built this out in the context of using SPIFFE but supporting multiple URI SANs sounds correct and a good way to go.

Happy to have a PR. Given this library's tiny surface area, breaking change is ok by me.

**Comment by alecholmes** [comment]
Created new v0.3.0 tag and release with the changes.
