### ISSUE TITLE
Rejects valid input

### ISSUE THREAD

**Issue by n12c** [alecholmes/xfccparser#5]
Example 1 from https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert is rejected:

```
_, err := xfccparser.ParseXFCCHeader("By=http://frontend.lyft.com;Hash=468ed33be74eee6556d90c0149c1309e9ba61d6425303443c0748a02dd8de688;Subject=\"/C=US/ST=CA/L=San Francisco/OU=Lyft/CN=Test Client\";URI=http://testclient.lyft.com")
fmt.Println(err.Error())
```

```
invalid subject in client cert 0: invalid subject: 0:10: unexpected token "="
```

Bug or the example is wrong?

**Comment by ohkinozomu** [comment]
Probably, this is an error in the Envoy documentation: https://github.com/envoyproxy/envoy/issues/9889
